[tool.poetry]
name = "atcoder"
version = "0.1.0"
description = ""
authors = ["s.hirose <shunichi_hirose@pj100.biz>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
online-judge-tools = "^11.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
